import pytest
from uuid import UUID

from shared_data_layer.repositories.documents import DocumentRepository
from shared_data_layer.testing.base import AsyncBaseTestCase
from shared_data_layer.testing.factories.users import UserFactory
from shared_data_layer.testing.factories.documents import DocumentFactory
from shared_data_layer.testing.factories.retrieval import ChunkFactory, RetrievalRunFactory
from shared_data_layer.testing.factories.workflow import WorkflowGraphFactory
from shared_data_layer.testing.factories.knowledge_graph import GraphEdgeFactory

from shared_data_layer.db.models.retrieval import RetrievalRunItem
from shared_data_layer.db.models.knowledge_graph import GraphEntity


@pytest.mark.asyncio
class TestIntegration(AsyncBaseTestCase):
    async def test_document_repository_flow(self, db_session):
        # 1. Create User
        user = await UserFactory.create_async(session=db_session)
        assert isinstance(user.id, UUID)

        # 2. Create Document with Chunks (auto-generated by factory)
        document = await DocumentFactory.create_async(session=db_session, owner_user_id=user.id)
        # chunk1 and chunk2 are now created automatically by DocumentFactory

        # 3. Use Repository
        # Refresh document to ensure chunks are visible
        await db_session.refresh(document, attribute_names=["chunks"])
        repo = DocumentRepository(db_session)
        doc_read = await repo.get_document_with_chunks(document.id)

        # 4. Verify
        assert doc_read is not None
        assert doc_read.id == document.id
        assert len(doc_read.chunks) == 2
        # assert doc_read.chunks[0].text == "Chunk 1" # Text is random now
        # assert doc_read.chunks[1].text == "Chunk 2"

    async def test_retrieval_factory_flow(self, db_session):
        # Create RetrievalRun, should auto-create items
        run = await RetrievalRunFactory.create_async(session=db_session)
        
        # Refresh to load relationships
        await db_session.refresh(run, attribute_names=["items"])
        
        assert isinstance(run.id, UUID)
        assert len(run.items) == 2
        assert isinstance(run.items[0], RetrievalRunItem)
        assert run.items[0].run_id == run.id

    async def test_workflow_factory_flow(self, db_session):
        # Create WorkflowGraph, should auto-create versions
        graph = await WorkflowGraphFactory.create_async(session=db_session)
        
        await db_session.refresh(graph, attribute_names=["versions"])
        
        assert len(graph.versions) == 1
        version = graph.versions[0]
        
        # Refresh version to load nodes and edges
        await db_session.refresh(version, attribute_names=["nodes", "edges"])
        
        assert len(version.nodes) == 2
        assert len(version.edges) == 1
        assert version.graph_id == graph.id

    async def test_knowledge_graph_factory_flow(self, db_session):
        # Create GraphEdge, should auto-create evidence
        # Note: GraphEdge needs source and target entities. 
        # Polyfactory should handle ForeignKeys if not explicitly set, 
        # but let's see if it auto-creates the entities too.
        # Based on docs, if __set_relationships__ is True (default), it might try.
        # But for FKs, it usually creates the related object if not provided.
        
        edge = await GraphEdgeFactory.create_async(session=db_session)
        
        await db_session.refresh(edge, attribute_names=["evidence", "source", "target"])
        
        assert isinstance(edge.id, UUID)
        assert isinstance(edge.source, GraphEntity)
        assert isinstance(edge.target, GraphEntity)
        assert len(edge.evidence) == 1
        assert edge.evidence[0].edge_id == edge.id
