"""align_models_with_design

Revision ID: 1fc8daf120c1
Revises: 334ec02d3b6d
Create Date: 2025-11-26 14:03:59.019216

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1fc8daf120c1"
down_revision: Union[str, None] = "334ec02d3b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
