"""align_models_with_design

Revision ID: 334ec02d3b6d
Revises: 20251125233000
Create Date: 2025-11-26 14:02:04.470187

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "334ec02d3b6d"
down_revision: Union[str, None] = "20251125233000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("content_hash", sa.String(), nullable=False))
    op.add_column("chunks", sa.Column("owner_user_id", sa.Uuid(), nullable=True))
    op.add_column(
        "chunks", sa.Column("country_code", sa.String(length=3), nullable=True)
    )
    op.add_column(
        "chunks",
        sa.Column("section_path", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "chunks",
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("chunks", sa.Column("text_tsv", postgresql.TSVECTOR(), nullable=True))
    op.add_column(
        "chunks",
        sa.Column(
            "table_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "chunks",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "graph_communities", sa.Column("community_key", sa.String(), nullable=False)
    )
    op.add_column("graph_communities", sa.Column("summary", sa.Text(), nullable=True))
    op.drop_column("graph_communities", "description")
    op.drop_column("graph_communities", "name")
    op.add_column("graph_edges", sa.Column("directional", sa.Boolean(), nullable=False))
    op.add_column(
        "graph_edges",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "graph_edges",
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "graph_edges",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column("graph_edges", sa.Column("algo_version", sa.String(), nullable=True))
    op.add_column("graph_entities", sa.Column("document_id", sa.UUID(), nullable=True))
    op.add_column("graph_entities", sa.Column("chunk_id", sa.UUID(), nullable=True))
    op.add_column(
        "graph_entities", sa.Column("algo_version", sa.String(), nullable=True)
    )
    op.add_column(
        "graph_entities",
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "graph_entities",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "graph_entities",
        sa.Column("labels", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "graph_entities",
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("graph_entities", sa.Column("score", sa.Float(), nullable=False))
    op.create_foreign_key(
        op.f("fk_graph_entities_chunk_id_chunks"),
        "graph_entities",
        "chunks",
        ["chunk_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_graph_entities_document_id_documents"),
        "graph_entities",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.alter_column(
        "pillar_answers",
        "answer_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "retrieval_runs",
        "filters",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column("workflow_edges", sa.Column("confidence", sa.Float(), nullable=False))
    op.add_column(
        "workflow_edges",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("workflow_graphs", sa.Column("status", sa.String(), nullable=False))
    op.add_column(
        "workflow_graphs",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "workflow_graphs",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("workflow_nodes", sa.Column("level", sa.String(), nullable=False))
    op.add_column("workflow_nodes", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "workflow_nodes",
        sa.Column(
            "preconditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "workflow_nodes",
        sa.Column("tool_hints", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "workflow_nodes",
        sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "workflow_nodes",
        "config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_versions",
        "definition",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_versions",
        "definition",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "workflow_nodes",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("workflow_nodes", "artifacts")
    op.drop_column("workflow_nodes", "tool_hints")
    op.drop_column("workflow_nodes", "preconditions")
    op.drop_column("workflow_nodes", "description")
    op.drop_column("workflow_nodes", "level")
    op.drop_column("workflow_graphs", "metadata")
    op.drop_column("workflow_graphs", "published_at")
    op.drop_column("workflow_graphs", "status")
    op.drop_column("workflow_edges", "metadata")
    op.drop_column("workflow_edges", "confidence")
    op.alter_column(
        "retrieval_runs",
        "filters",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "pillar_answers",
        "answer_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_graph_entities_document_id_documents"),
        "graph_entities",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_graph_entities_chunk_id_chunks"), "graph_entities", type_="foreignkey"
    )
    op.drop_column("graph_entities", "score")
    op.drop_column("graph_entities", "properties")
    op.drop_column("graph_entities", "labels")
    op.drop_column("graph_entities", "last_seen_at")
    op.drop_column("graph_entities", "first_seen_at")
    op.drop_column("graph_entities", "algo_version")
    op.drop_column("graph_entities", "chunk_id")
    op.drop_column("graph_entities", "document_id")
    op.drop_column("graph_edges", "algo_version")
    op.drop_column("graph_edges", "last_seen_at")
    op.drop_column("graph_edges", "first_seen_at")
    op.drop_column("graph_edges", "metadata")
    op.drop_column("graph_edges", "directional")
    op.add_column(
        "graph_communities",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "graph_communities",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("graph_communities", "summary")
    op.drop_column("graph_communities", "community_key")
    op.alter_column(
        "chunks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("chunks", "table_payload")
    op.drop_column("chunks", "text_tsv")
    op.drop_column("chunks", "bbox")
    op.drop_column("chunks", "section_path")
    op.drop_column("chunks", "country_code")
    op.drop_column("chunks", "owner_user_id")
    op.drop_column("chunks", "content_hash")
    # ### end Alembic commands ###
