"""Initial migration

Revision ID: 3d2859a21d27
Revises: 
Create Date: 2025-11-25 17:37:50.156120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d2859a21d27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('access_scope', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ingestion_stage', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('managed_by', sa.String(), nullable=True),
    sa.Column('active_chat_refs', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('owner_user_id', 'content_hash', name='uq_documents_owner_content_hash')
    )
    op.create_table('graph_communities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_communities'))
    )
    op.create_table('retrieval_runs',
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_runs'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflow_graphs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_graphs'))
    )
    op.create_table('artifacts',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('s3_uri', sa.String(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_artifacts_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_table('chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('artifact_uri', sa.String(), nullable=True),
    sa.Column('schema_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_table('conversation_documents',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('attached_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('attach_source', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('visibility_override', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_conversation_documents_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_documents')),
    sa.UniqueConstraint('conversation_id', 'document_id', name='uq_conversation_documents_conv_doc')
    )
    op.create_table('graph_entities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_graph_entities_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_entities'))
    )
    op.create_index(op.f('ix_graph_entities_country_code'), 'graph_entities', ['country_code'], unique=False)
    op.create_index(op.f('ix_graph_entities_name'), 'graph_entities', ['name'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('last_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_table('workflow_versions',
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['workflow_graphs.id'], name=op.f('fk_workflow_versions_graph_id_workflow_graphs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_versions'))
    )
    op.create_table('chunk_metrics',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('last_retrieved_at', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_chunk_metrics_chunk_id_chunks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_metrics')),
    sa.UniqueConstraint('chunk_id', name=op.f('uq_chunk_metrics_chunk_id'))
    )
    op.create_table('graph_edges',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph_entities.id'], name=op.f('fk_graph_edges_source_id_graph_entities')),
    sa.ForeignKeyConstraint(['target_id'], ['graph_entities.id'], name=op.f('fk_graph_edges_target_id_graph_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    op.create_table('retrieval_run_items',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_retrieval_run_items_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['run_id'], ['retrieval_runs.id'], name=op.f('fk_retrieval_run_items_run_id_retrieval_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_run_items'))
    )
    op.create_table('workflow_edges',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_edges_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges'))
    )
    op.create_table('workflow_nodes',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], name=op.f('fk_workflow_nodes_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes'))
    )
    op.create_table('graph_evidence',
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_graph_evidence_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['edge_id'], ['graph_edges.id'], name=op.f('fk_graph_evidence_edge_id_graph_edges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_evidence')
    op.drop_table('workflow_nodes')
    op.drop_table('workflow_edges')
    op.drop_table('retrieval_run_items')
    op.drop_table('graph_edges')
    op.drop_table('chunk_metrics')
    op.drop_table('workflow_versions')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_graph_entities_name'), table_name='graph_entities')
    op.drop_index(op.f('ix_graph_entities_country_code'), table_name='graph_entities')
    op.drop_table('graph_entities')
    op.drop_table('conversation_documents')
    op.drop_table('chunks')
    op.drop_table('artifacts')
    op.drop_table('workflow_graphs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('retrieval_runs')
    op.drop_table('graph_communities')
    op.drop_table('documents')
    # ### end Alembic commands ###
